apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-vote
  labels:
    app: {{ .Release.Name }}-vote
spec:
  type: {{ .Values.vote.service.type }}
  ports:
    - port: {{ .Values.vote.service.port }}
      targetPort: {{ .Values.vote.service.targetPort }}
  selector:
    app: {{ .Release.Name }}-vote